# Generated by Django 3.0.7 on 2020-06-25 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0003_vehicle_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='requested_driver',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
