# Generated by Django 3.0.7 on 2020-06-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0005_auto_20200625_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='key_color',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Red'), (2, 'Blue'), (3, 'Green'), (4, 'Yellow'), (5, 'White')], default=0, verbose_name='Key Tag Color'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'None'), (1, 'Active'), (2, 'Inactive'), (3, 'Retired')], default=1, verbose_name='Status'),
        ),
    ]
