# Generated by Django 3.0.7 on 2020-07-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0008_auto_20200705_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['num']},
        ),
        migrations.RemoveField(
            model_name='triprequest',
            name='key_num',
        ),
        migrations.AddField(
            model_name='triprequest',
            name='signed_off',
            field=models.DateField(blank=True, null=True, verbose_name='Signed Off On'),
        ),
    ]
